# Generated by Django 3.2.4 on 2021-07-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='TypeIdentify',
            field=models.CharField(blank=True, choices=[('CED', 'CÉDULA'), ('RUC', 'REGISTRO UNICO CONTRIBUYENTE'), ('PAS', 'PASAPORTE')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identify',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
